### PR TITLE
Remove build process and fix colors

### PR DESCRIPTION
**Pull request by alshakero**
Just noticed the diff is broken because I renamed the files. I'll revert the names and willl re-rename them after approval.

### CODE REVIEW

**Comment by warpech** [comment]
I will update the color demos in index.html, too.

@alshakero was the minified file removed on purpose?

**Comment by alshakero** [comment]
@warpech yes because build process is gone and the minified file is outdated now.

**Comment by warpech** [comment]
But how to create the minified file now? Webpack does not work anymore.

```
 npm run build

> uniform.css@0.0.4 build C:\www\uniform.css
> webpack

No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.
```

All apps are looking for the file `uniform.css` so it better be at that path.

**Comment by alshakero** [comment]
> All apps are looking for the file uniform.css so it better be at that path.

Of course, I'll do the needed renaming. In fact I already did it but this ruined GH diffing so I reverted so you could review. I'll re-rename now.

**Comment by alshakero** [comment]
> Lgtm, but please fix the minified file after merging to master

There won't be any renamed files. I'm kinda lost here. 

No build => no minified files. 

However, a unminified file is present where the apps need it.

**Pull request merged**
